version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/crewhub-frontend

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
